=== Shabaltas/javaWEB/task4/data/Banks.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema  xmlns="http://www.w3.org/2001/XMLSchema"
		 targetNamespace="http://www.example.com/Banks"
		 xmlns:tns="http://www.example.com/Banks"
		 elementFormDefault="qualified">
	<element name="deposit" type="tns:Deposit" abstract="true"/>
	<element name="depositForNaturalPerson" type="tns:DepositForNaturalPerson" substitutionGroup="tns:deposit"/>
	<element name="depositForJuridicalPerson" type="tns:DepositForJuridicalPerson" substitutionGroup="tns:deposit"/>
	<element name="Banks">
		<complexType>
			<sequence>
				<element ref="tns:deposit"  minOccurs="16" maxOccurs="unbounded"/>
			</sequence>
		</complexType>
	</element>
	<complexType name="Deposit">
		<sequence>
			<element name="bankName" type="string"/>
			<element name="country" type="string" default="Belarus"/>
			<element name="profitability" type="float"/>
			<element name="dateOfDeposit" type="date"/>
			<element name="duration" default="P1Y">
				<simpleType>
					<restriction base="duration">
						<pattern value="P(\d+Y)?(\d+M)?(\d+D)?(T0H0M0S)?"/>
					</restriction>
				</simpleType>
			</element>
		</sequence>
		<attribute name="depositType" use="required">
			<simpleType>
				<restriction base="string">
					<enumeration value="poste restante"/>
					<enumeration value="urgent"/>
					<enumeration value="settlement"/>
					<enumeration value="accumulative"/>
					<enumeration value="saving"/>
					<enumeration value="metallic"/>
				</restriction>
			</simpleType>
		</attribute>
		<attribute name="accountID" type="ID" use="required"/>
	</complexType>
	<complexType name="DepositForNaturalPerson">
		<complexContent>
			<extension base="tns:Deposit">
				<sequence>
					<element name="depositor" type="tns:SNP"/>
					<element name="amount">
						<simpleType>
							<restriction base="decimal">
								<minInclusive value="100"/>
							</restriction>
						</simpleType>
					</element>
				</sequence>
			</extension>
		</complexContent>
	</complexType>
	<complexType name="DepositForJuridicalPerson">
		<complexContent>
			<extension base="tns:Deposit">
				<sequence>
					<element name="contactPerson" type="tns:SNP"/>
					<element name="amount">
						<simpleType>
							<restriction base="decimal">
								<minInclusive value="10000"/>
							</restriction>
						</simpleType>
					</element>
					<element name="companyName" type="string"/>
					<element name="companyLocation" type="string"/>
				</sequence>
			</extension>
		</complexContent>
	</complexType>
	<complexType name="SNP">
		<sequence>
			<element name="surname" type="string" />
			<element name="name" type="string"/>
			<element name="patronymic" type="string"/>
		</sequence>
	</complexType>
</schema>

=== Shabaltas/javaWEB/task4/data/Banks2.xml
<Banks xmlns:tns="http://www.w3.org/2001/XMLSchema-instance"
	   xmlns="http://www.example.com/Banks"
	   tns:schemaLocation="http://www.example.com/Banks Banks.xsd">
	<depositForNaturalPerson depositType="accumulative" accountID="AE123">
		<bankName>ALFA</bankName>
		<country>Belarus</country>
		<profitability>0.8E1</profitability>
		<dateOfDeposit>2012-02-12</dateOfDeposit>
		<duration>P1Y2M</duration>
		<depositor>
			<surname>Shved</surname>
			<name>Elizaveta</name>
			<patronymic>Yurevna</patronymic>
		</depositor>
		<amount>123</amount>
	</depositForNaturalPerson>
	<depositForJuridicalPerson depositType="saving" accountID="SG123">
		<bankName>BPS</bankName>
		<country>Russia</country>
		<profitability>9.3</profitability>
		<dateOfDeposit>2013-02-26</dateOfDeposit>
		<duration>P2D</duration>
		<contactPerson>
			<surname>Fando</surname>
			<name>Pavel</name>
			<patronymic>Olegovich</patronymic>
		</contactPerson>
		<amount>180000</amount>
		<companyName>MetroLove</companyName>
		<companyLocation>Minsk</companyLocation>
	</depositForJuridicalPerson>
	<depositForJuridicalPerson depositType="saving" accountID="SG127">
		<bankName>BPS</bankName>
		<country>Russia</country>
		<profitability>9.3</profitability>
		<dateOfDeposit>2013-02-26</dateOfDeposit>
		<duration>P2D</duration>
		<contactPerson>
			<surname>gr</surname>
			<name>rg</name>
			<patronymic>gr</patronymic>
		</contactPerson>
		<amount>180000</amount>
		<companyName>somename</companyName>
		<companyLocation>Minsk</companyLocation>
	</depositForJuridicalPerson>
	<depositForJuridicalPerson depositType="saving" accountID="S123">
		<bankName>BPS</bankName>
		<country>Russia</country>
		<profitability>9.3</profitability>
		<dateOfDeposit>2013-02-26</dateOfDeposit>
		<duration>P2D</duration>
		<contactPerson>
			<surname>gr</surname>
			<name>rg</name>
			<patronymic>gr</patronymic>
		</contactPerson>
		<amount>180000</amount>
		<companyName>somename</companyName>
		<companyLocation>Minsk</companyLocation>
	</depositForJuridicalPerson>
	<depositForNaturalPerson depositType="accumulative" accountID="AE3">
		<bankName>ALFA</bankName>
		<country>h</country>
		<profitability>1.5E2</profitability>
		<dateOfDeposit>2012-02-12</dateOfDeposit>
		<duration>P1Y</duration>
		<depositor>
			<surname>surname</surname>
			<name>name</name>
			<patronymic>d</patronymic>
		</depositor>
		<amount>123</amount>
	</depositForNaturalPerson>
	<depositForNaturalPerson depositType="accumulative" accountID="AE23">
		<bankName>ALFA</bankName>
		<country>h</country>
		<profitability>1.5E2</profitability>
		<dateOfDeposit>2012-02-12</dateOfDeposit>
		<duration>P1Y</duration>
		<depositor>
			<surname>surname</surname>
			<name>name</name>
			<patronymic>d</patronymic>
		</depositor>
		<amount>123</amount>
	</depositForNaturalPerson>
	<depositForJuridicalPerson depositType="saving" accountID="S1238">
		<bankName>BPS</bankName>
		<country>Russia</country>
		<profitability>9.3</profitability>
		<dateOfDeposit>2013-02-26</dateOfDeposit>
		<duration>P2D</duration>
		<contactPerson>
			<surname>gr</surname>
			<name>rg</name>
			<patronymic>gr</patronymic>
		</contactPerson>
		<amount>180000</amount>
		<companyName>somename</companyName>
		<companyLocation>Minsk</companyLocation>
	</depositForJuridicalPerson>
	<depositForJuridicalPerson depositType="settlement" accountID="ST1253">
		<bankName>BPS</bankName>
		<country>Russia</country>
		<profitability>9.3</profitability>
		<dateOfDeposit>2013-02-26</dateOfDeposit>
		<duration>P2D</duration>
		<contactPerson>
			<surname>gr</surname>
			<name>rg</name>
			<patronymic>gr</patronymic>
		</contactPerson>
		<amount>180000</amount>
		<companyName>somename</companyName>
		<companyLocation>Minsk</companyLocation>
	</depositForJuridicalPerson>
	<depositForNaturalPerson depositType="accumulative" accountID="AE123">
		<bankName>ALFA</bankName>
		<country>Belarus</country>
		<profitability>9.7</profitability>
		<dateOfDeposit>2015-02-12</dateOfDeposit>
		<duration>P400D</duration>
		<depositor>
			<surname>Golubtsov</surname>
			<name>Mark</name>
			<patronymic>Sergeevich</patronymic>
		</depositor>
		<amount>2000</amount>
	</depositForNaturalPerson>
	<depositForJuridicalPerson depositType="urgent" accountID="UT123">
		<bankName>BPS</bankName>
		<country>Russia</country>
		<profitability>11/2</profitability>
		<dateOfDeposit>2013-02-26</dateOfDeposit>
		<duration>P9M</duration>
		<contactPerson>
			<surname>Yagmin</surname>
			<name>Pavel</name>
			<patronymic>Olegovich</patronymic>
		</contactPerson>
		<amount>280000</amount>
		<companyName>CHSV</companyName>
		<companyLocation>Brest</companyLocation>
	</depositForJuridicalPerson>
	<depositForJuridicalPerson depositType="metallic" accountID="MC1203">
		<bankName>Belarusbank</bankName>
		<country></country>
		<profitability>9.3</profitability>
		<dateOfDeposit>2014-02-26</dateOfDeposit>
		<duration>P2Y6M</duration>
		<contactPerson>
			<surname>Yakovlevich</surname>
			<name>Pavel</name>
			<patronymic>Olegovich</patronymic>
		</contactPerson>
		<amount>390000</amount>
		<companyName>IDK</companyName>
		<companyLocation>Minsk</companyLocation>
	</depositForJuridicalPerson>
	<depositForJuridicalPerson depositType="poste restante" accountID="PR193">
		<bankName>MoskvaBank</bankName>
		<country>Russia</country>
		<profitability>9.3</profitability>
		<dateOfDeposit>2013-02-26</dateOfDeposit>
		<duration>P2D</duration>
		<contactPerson>
			<surname>Kordukoff</surname>
			<name>Anhdrey</name>
			<patronymic>Aleksandrovich</patronymic>
		</contactPerson>
		<amount>180000</amount>
		<companyName>SULATER</companyName>
		<companyLocation>Moskva</companyLocation>
	</depositForJuridicalPerson>
	<depositForNaturalPerson depositType="accumulative" accountID="AE933">
		<bankName>ALFA</bankName>
		<country></country>
		<profitability>9.3</profitability>
		<dateOfDeposit>2018-11-12</dateOfDeposit>
		<duration>P45D</duration>
		<depositor>
			<surname>Chrapich</surname>
			<name>Diana</name>
			<patronymic>Andreevna</patronymic>
		</depositor>
		<amount>1500</amount>
	</depositForNaturalPerson>
	<depositForNaturalPerson depositType="accumulative" accountID="AE2803">
		<bankName>ALFA</bankName>
		<country>Ukraine</country>
		<profitability>1.03E1</profitability>
		<dateOfDeposit>2014-02-25</dateOfDeposit>
		<duration>P1Y2M</duration>
		<depositor>
			<surname>Popov</surname>
			<name>Eugene</name>
			<patronymic>Yurevich</patronymic>
		</depositor>
		<amount>1890</amount>
	</depositForNaturalPerson>
	<depositForJuridicalPerson depositType="metallic" accountID="MC8008">
		<bankName>VTB</bankName>
		<country>Russia</country>
		<profitability>9.3</profitability>
		<dateOfDeposit>2013-05-26</dateOfDeposit>
		<duration>P2M</duration>
		<contactPerson>
			<surname>Ivanov</surname>
			<name>Ivan</name>
			<patronymic>Petrovich</patronymic>
		</contactPerson>
		<amount>180000</amount>
		<companyName>Nut&amp;Ella</companyName>
		<companyLocation>Saint-Petersburg</companyLocation>
	</depositForJuridicalPerson>
	<depositForJuridicalPerson depositType="saving" accountID="SG1203">
		<bankName>BPS</bankName>
		<country>Belarus</country>
		<profitability>9.3</profitability>
		<dateOfDeposit>2013-02-26</dateOfDeposit>
		<duration>P2Y</duration>
		<contactPerson>
			<surname>Shabaltas</surname>
			<name>Angelina</name>
			<patronymic>Yurevna</patronymic>
		</contactPerson>
		<amount>180000</amount>
		<companyName>CompLina</companyName>
		<companyLocation>Minsk</companyLocation>
	</depositForJuridicalPerson>
</Banks>
